#!/usr/bin/env python3
from __future__ import annotations

from html.parser import HTMLParser
from pathlib import Path
from urllib.parse import parse_qs, unquote, urlsplit
import json
import re
import sys

ROOT = Path(__file__).resolve().parent
APP_ROOT = ROOT.parent
SITE_ROOT = "https://alice51849.github.io/zodira-support/"
PAGES = {
    "index.html": SITE_ROOT,
    "privacy.html": f"{SITE_ROOT}privacy.html",
    "terms.html": f"{SITE_ROOT}terms.html",
}
OFFICIAL_LOCALES = (
    "ar-SA", "bn-BD", "ca", "zh-Hans", "zh-Hant", "hr", "cs", "da",
    "nl-NL", "en-AU", "en-CA", "en-GB", "en-US", "fi", "fr-CA",
    "fr-FR", "de-DE", "el", "gu-IN", "he", "hi", "hu", "id", "it",
    "ja", "kn-IN", "ko", "ms", "ml-IN", "mr-IN", "no", "or-IN", "pl",
    "pt-BR", "pt-PT", "pa-IN", "ro", "ru", "sk", "sl-SI", "es-MX",
    "es-ES", "sv", "ta-IN", "te-IN", "th", "tr", "uk", "ur-PK", "vi",
)
LOCALE_SET = frozenset(OFFICIAL_LOCALES)
REQUIRED_LOCALE_KEYS = frozenset(
    {
        "languageName", "name", "subtitle", "description", "workflow",
        "support", "privacy", "local", "lens", "purchase", "noSubscription",
        "restore", "delete", "noCollection", "deletion", "restoreHelp",
        "titleSupport", "titlePrivacy",
    }
)
CRITICAL_TRANSLATED_KEYS = (
    "support", "privacy", "local", "lens", "purchase", "noSubscription",
    "restore", "delete", "noCollection", "deletion",
)
SCRIPT_MARKERS = {
    "ar-SA": r"[\u0600-\u06ff]",
    "bn-BD": r"[\u0980-\u09ff]",
    "zh-Hans": r"[\u3400-\u9fff]",
    "zh-Hant": r"[\u3400-\u9fff]",
    "el": r"[\u0370-\u03ff]",
    "gu-IN": r"[\u0a80-\u0aff]",
    "he": r"[\u0590-\u05ff]",
    "hi": r"[\u0900-\u097f]",
    "ja": r"[\u3040-\u30ff]",
    "kn-IN": r"[\u0c80-\u0cff]",
    "ko": r"[\uac00-\ud7af]",
    "ml-IN": r"[\u0d00-\u0d7f]",
    "mr-IN": r"[\u0900-\u097f]",
    "or-IN": r"[\u0b00-\u0b7f]",
    "pa-IN": r"[\u0a00-\u0a7f]",
    "ru": r"[\u0400-\u04ff]",
    "ta-IN": r"[\u0b80-\u0bff]",
    "te-IN": r"[\u0c00-\u0c7f]",
    "th": r"[\u0e00-\u0e7f]",
    "uk": r"[\u0400-\u04ff]",
    "ur-PK": r"[\u0600-\u06ff]",
}
CANONICAL_METADATA = APP_ROOT / "StoreAssets/metadata/build15-exact50.json"
FASTLANE_METADATA = APP_ROOT / "fastlane/metadata"
BACKUP_METADATA = APP_ROOT / "fastlane/metadata_backup_aso"
URL_BUILDER = APP_ROOT / "tools/build_asc_meta.py"
ALLOWED_EMAIL = "hourstag.app@gmail.com"
BUNDLE_ID = "com.alice51849." + "Astrea"
EMAIL_RE = re.compile(r"[\w.+-]+@[\w.-]+\.[A-Za-z]{2,}")
PLACEHOLDER_RE = re.compile(
    r"\b(?:TODO|TBD|PLACEHOLDER|TRANSLATION NEEDED)\b|"
    r"\{\{[^}]+\}\}|\[\[[^\]]+\]\]|<missing>",
)
LEGACY_TOKENS = (
    "astrea" + "-support",
    "sup_" + "astrea",
    "legacy public" + " path",
)


class PageParser(HTMLParser):
    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.hrefs: list[str] = []
        self.ids: set[str] = set()
        self.canonical: list[str] = []
        self.alternates: dict[str, list[str]] = {}
        self.i18n_keys: set[str] = set()
        self.html_lang = ""
        self.html_data_pages: list[str] = []
        self.html_count = 0
        self.h1_count = 0
        self.has_viewport = False

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        values = {key: value or "" for key, value in attrs}
        if tag == "html":
            self.html_count += 1
            self.html_lang = values.get("lang", "")
            self.html_data_pages.extend(
                value or ""
                for key, value in attrs
                if key == "data-page"
            )
        if tag == "meta" and values.get("name", "").casefold() == "viewport":
            self.has_viewport = bool(values.get("content"))
        if tag == "a" and values.get("href"):
            self.hrefs.append(values["href"])
        if tag == "script" and values.get("src"):
            self.hrefs.append(values["src"])
        if values.get("id"):
            self.ids.add(values["id"])
        if values.get("data-i18n"):
            self.i18n_keys.add(values["data-i18n"])
        if values.get("data-i18n-content"):
            self.i18n_keys.add(values["data-i18n-content"])
        if tag == "link" and values.get("href"):
            relation = values.get("rel", "").casefold()
            if relation == "canonical":
                self.canonical.append(values["href"])
            elif relation == "alternate" and values.get("hreflang"):
                self.alternates.setdefault(values["hreflang"], []).append(
                    values["href"]
                )
            else:
                self.hrefs.append(values["href"])
        if tag == "h1":
            self.h1_count += 1


def expected_support_url(locale: str) -> str:
    return f"{SITE_ROOT}?lang={locale}"


def expected_privacy_url(locale: str) -> str:
    return f"{SITE_ROOT}privacy.html?lang={locale}"


# Static per-locale surfaces generated by tools/support_surfaces.py. They are the
# exact-50 support/privacy/index indexing contract. The query-string URLs above
# remain immutable external entry points and migrate to these static routes.
STATIC_SURFACES = ("index.html", "support.html", "privacy.html")


def expected_static_urls() -> set[str]:
    return {
        f"{SITE_ROOT}{locale}/{name}"
        for locale in OFFICIAL_LOCALES
        for name in STATIC_SURFACES
    }


def parse_locales() -> tuple[dict[str, dict[str, str]], list[str]]:
    errors: list[str] = []
    path = ROOT / "locales.js"
    source = path.read_text(encoding="utf-8")
    prefix = "window.ZODIRA_LOCALES = "
    if not source.startswith(prefix) or not source.endswith(";\n"):
        return {}, ["locales.js: expected one explicit local dictionary assignment"]
    try:
        locales = json.loads(source[len(prefix):-2])
    except json.JSONDecodeError as error:
        return {}, [f"locales.js: invalid dictionary JSON: {error}"]
    if set(locales) != LOCALE_SET:
        errors.append(
            "locales.js: exact-50 mismatch "
            f"missing={sorted(LOCALE_SET - set(locales))} "
            f"extra={sorted(set(locales) - LOCALE_SET)}"
        )
        return locales, errors

    english = locales["en-US"]
    for locale in OFFICIAL_LOCALES:
        record = locales[locale]
        if not isinstance(record, dict) or set(record) != REQUIRED_LOCALE_KEYS:
            errors.append(f"locales.js: {locale} schema mismatch")
            continue
        for key, value in record.items():
            if not isinstance(value, str) or not value.strip():
                errors.append(f"locales.js: {locale}/{key} is empty")
            elif "\ufffd" in value or PLACEHOLDER_RE.search(value):
                errors.append(f"locales.js: {locale}/{key} has placeholder text")
            elif value.strip() in REQUIRED_LOCALE_KEYS:
                errors.append(f"locales.js: {locale}/{key} exposes a raw key")
        if not locale.startswith("en-"):
            for key in CRITICAL_TRANSLATED_KEYS:
                if record.get(key) == english.get(key):
                    errors.append(
                        f"locales.js: {locale}/{key} falls back to en-US"
                    )
        marker = SCRIPT_MARKERS.get(locale)
        if marker:
            critical = " ".join(record.get(key, "") for key in CRITICAL_TRANSLATED_KEYS)
            if not re.search(marker, critical):
                errors.append(f"locales.js: {locale} lacks its native script")
    return locales, errors


def lint_page(
    name: str,
    canonical: str,
    locale_keys: set[str],
) -> list[str]:
    errors: list[str] = []
    path = ROOT / name
    source = path.read_text(encoding="utf-8")
    parser = PageParser()
    parser.feed(source)
    parser.close()

    if not source.lstrip().casefold().startswith("<!doctype html>"):
        errors.append(f"{name}: missing HTML5 doctype")
    expected_lang = "en-US" if name in {"index.html", "privacy.html"} else "en"
    if parser.html_lang != expected_lang:
        errors.append(f"{name}: html lang must be {expected_lang}")
    expected_surface = ROOT_PAGE_SURFACES.get(name)
    if (
        expected_surface is not None
        and (
            parser.html_count != 1
            or parser.html_data_pages != [expected_surface]
        )
    ):
        errors.append(
            f"{name}: html data-page must be exactly {expected_surface}"
        )
    if not parser.has_viewport:
        errors.append(f"{name}: missing viewport metadata")
    if parser.h1_count != 1:
        errors.append(f"{name}: expected one h1, found {parser.h1_count}")
    if parser.canonical != [canonical]:
        errors.append(f"{name}: canonical mismatch {parser.canonical!r}")
    if unknown := sorted(parser.i18n_keys - locale_keys):
        errors.append(f"{name}: unknown locale keys {unknown}")
    if name in {"index.html", "privacy.html"}:
        if parser.alternates.get("x-default") != [canonical]:
            errors.append(f"{name}: x-default must match the root canonical")
        for required_asset in ("locales.js", "localize.js"):
            if required_asset not in parser.hrefs:
                errors.append(f"{name}: missing {required_asset}")
        if 'id="locale-select"' not in source:
            errors.append(f"{name}: missing exact locale selector")

    for email in EMAIL_RE.findall(source):
        if email.casefold() != ALLOWED_EMAIL:
            errors.append(f"{name}: disallowed public email {email}")
    for href in parser.hrefs:
        parsed = urlsplit(href)
        if parsed.scheme in {"https", "mailto"}:
            if parsed.scheme == "mailto":
                address = unquote(parsed.path).casefold()
                if address != ALLOWED_EMAIL:
                    errors.append(f"{name}: disallowed mailto address {address}")
            continue
        if parsed.scheme or parsed.netloc:
            errors.append(f"{name}: unsupported link {href}")
            continue
        if not parsed.path:
            if parsed.fragment and parsed.fragment not in parser.ids:
                errors.append(f"{name}: missing local anchor #{parsed.fragment}")
            continue
        target = (path.parent / unquote(parsed.path)).resolve()
        if ROOT not in target.parents and target != ROOT:
            errors.append(f"{name}: link escapes site root: {href}")
        elif not target.is_file():
            errors.append(f"{name}: broken local link {href}")
    return errors


class ContainerAnchorParser(HTMLParser):
    def __init__(self, container_tag: str, class_name: str) -> None:
        super().__init__(convert_charrefs=True)
        self.container_tag = container_tag
        self.class_name = class_name
        self.in_container = False
        self.current: dict[str, str] | None = None
        self.current_text: list[str] = []
        self.anchors: list[dict[str, str]] = []

    def handle_starttag(self, tag: str,
                        attrs: list[tuple[str, str | None]]) -> None:
        values = {key: value or "" for key, value in attrs}
        if (tag == self.container_tag
                and self.class_name in values.get("class", "").split()):
            self.in_container = True
        elif self.in_container and tag == "a":
            self.current = values
            self.current_text = []

    def handle_data(self, data: str) -> None:
        if self.current is not None:
            self.current_text.append(data)

    def handle_endtag(self, tag: str) -> None:
        if tag == "a" and self.current is not None:
            self.current["text"] = " ".join("".join(self.current_text).split())
            self.anchors.append(self.current)
            self.current = None
            self.current_text = []
        elif tag == self.container_tag and self.in_container:
            self.in_container = False


class AnchorHrefParser(HTMLParser):
    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.hrefs: list[str] = []

    def handle_starttag(self, tag: str,
                        attrs: list[tuple[str, str | None]]) -> None:
        if tag != "a":
            return
        values = {key: value or "" for key, value in attrs}
        if values.get("href"):
            self.hrefs.append(values["href"])


ROOT_NAV_CONTRACTS = {
    "index.html": (
        ("index.html", "support", True),
        ("privacy.html", "privacy", False),
    ),
    "privacy.html": (
        ("index.html", "support", False),
        ("privacy.html", "privacy", True),
    ),
}
ROOT_STATIC_ENTRIES = {
    "index.html": ("en-US/support.html", "Localized support pages"),
    "privacy.html": ("en-US/privacy.html", "Localized privacy pages"),
}
ROOT_PAGE_SURFACES = {
    "index.html": "index",
    "privacy.html": "privacy",
}


def lint_root_navs(locales: dict[str, dict[str, str]]) -> list[str]:
    errors: list[str] = []
    for name, contract in ROOT_NAV_CONTRACTS.items():
        parser = ContainerAnchorParser("nav", "nav")
        parser.feed((ROOT / name).read_text(encoding="utf-8"))
        parser.close()
        if len(parser.anchors) != len(contract):
            errors.append(f"{name}: root nav must contain exactly support and privacy")
            continue

        destinations: list[str] = []
        for anchor, (href, key, current) in zip(parser.anchors, contract):
            destinations.append(anchor.get("href", ""))
            if anchor.get("href") != href or anchor.get("data-i18n") != key:
                errors.append(f"{name}: root nav destination contract mismatch")
            if (anchor.get("aria-current") == "page") != current:
                errors.append(f"{name}: root nav current-page state mismatch")
            if "data-surface" in anchor or "data-localized-link" in anchor:
                errors.append(f"{name}: root nav must stay static and unambiguous")
        if len(destinations) != len(set(destinations)):
            errors.append(f"{name}: root nav has duplicate destinations")

        for locale, copy in locales.items():
            labels = [
                " ".join(copy[key].split()).casefold()
                for _, key, _ in contract
            ]
            if len(labels) != len(set(labels)):
                errors.append(f"{name}: duplicate visible nav label in {locale}")
    return errors


def site_anchor_target(current: str, href: str) -> str | None:
    if not href or href.startswith(("#", "mailto:", "tel:")):
        return None
    parsed = urlsplit(href)
    site = urlsplit(SITE_ROOT)
    if parsed.scheme in {"http", "https"}:
        if parsed.scheme != site.scheme or parsed.netloc != site.netloc:
            return None
        if not parsed.path.startswith(site.path):
            return None
        relative = unquote(parsed.path[len(site.path):])
    elif parsed.scheme or parsed.netloc:
        return None
    else:
        relative = (Path(current).parent / unquote(parsed.path)).as_posix()

    target = (ROOT / relative).resolve()
    if not target.suffix:
        target /= "index.html"
    if target != ROOT and ROOT not in target.parents:
        return None
    return target.relative_to(ROOT).as_posix()


def lint_root_static_graph(locales: dict[str, dict[str, str]]) -> list[str]:
    errors: list[str] = []
    required = {
        f"{locale}/{surface}"
        for locale in OFFICIAL_LOCALES
        for surface in STATIC_SURFACES
    }
    for name, (expected_href, expected_label) in ROOT_STATIC_ENTRIES.items():
        source = (ROOT / name).read_text(encoding="utf-8")
        parser = ContainerAnchorParser("div", "footer-links")
        parser.feed(source)
        parser.close()
        rendered_labels = []
        for anchor in parser.anchors:
            key = anchor.get("data-i18n")
            label = locales["en-US"].get(key, "") if key else anchor.get("text", "")
            rendered_labels.append(" ".join(label.split()).casefold())
        if len(rendered_labels) != len(set(rendered_labels)):
            errors.append(f"{name}: footer links have duplicate visible labels")

        static_anchors = [
            anchor for anchor in parser.anchors
            if site_anchor_target(name, anchor.get("href", "")) in required
        ]
        if [(anchor.get("href"), anchor.get("text")) for anchor in static_anchors] != [
            (expected_href, expected_label)
        ]:
            errors.append(f"{name}: static footer entry contract mismatch")
        expected_marker = (
            f'<!-- root-static-entry:start --><a href="{expected_href}">'
            f'{expected_label}</a><!-- root-static-entry:end -->'
        )
        if source.count(expected_marker) != 1:
            errors.append(f"{name}: generated static footer entry is stale")

    nodes = required | set(ROOT_STATIC_ENTRIES)
    reached = set(ROOT_STATIC_ENTRIES)
    pending = list(reached)
    while pending:
        current = pending.pop()
        path = ROOT / current
        if not path.is_file():
            continue
        parser = AnchorHrefParser()
        parser.feed(path.read_text(encoding="utf-8"))
        parser.close()
        for href in parser.hrefs:
            target = site_anchor_target(current, href)
            if target in nodes and target not in reached:
                reached.add(target)
                pending.append(target)

    unreachable = sorted(required - reached)
    if unreachable:
        errors.append(
            f"root anchor graph reaches {len(required) - len(unreachable)}/"
            f"{len(required)} required surfaces; missing={unreachable[:10]}"
        )
    return errors


def lint_static_surfaces() -> list[str]:
    errors: list[str] = []
    canonical_owners: dict[str, list[str]] = {}
    for locale in OFFICIAL_LOCALES:
        for name in STATIC_SURFACES:
            relative = f"{locale}/{name}"
            path = ROOT / relative
            if not path.is_file():
                errors.append(f"{relative}: missing static surface")
                continue
            parser = PageParser()
            parser.feed(path.read_text(encoding="utf-8"))
            parser.close()
            expected = f"{SITE_ROOT}{relative}"
            if parser.canonical != [expected]:
                errors.append(f"{relative}: static canonical mismatch")
            else:
                canonical_owners.setdefault(expected, []).append(relative)
            expected_default = f"{SITE_ROOT}en-US/{name}"
            if parser.alternates.get("x-default") != [expected_default]:
                errors.append(f"{relative}: static x-default mismatch")

    expected_count = len(OFFICIAL_LOCALES) * len(STATIC_SURFACES)
    if len(canonical_owners) != expected_count:
        errors.append("static surfaces: canonical targets are not unique")
    for canonical, owners in canonical_owners.items():
        if len(owners) != 1:
            errors.append(f"static surfaces: canonical {canonical} owned by {owners}")
    return errors


def frozen_js_map(source: str, name: str) -> dict[str, str]:
    match = re.search(
        rf"const\s+{re.escape(name)}\s*=\s*Object\.freeze\((\{{.*?\}})\);",
        source,
        re.S,
    )
    if not match:
        return {}
    try:
        value = json.loads(match.group(1))
    except json.JSONDecodeError:
        return {}
    return value if isinstance(value, dict) else {}


def lint_legacy_router() -> list[str]:
    errors: list[str] = []
    source = (ROOT / "localize.js").read_text(encoding="utf-8")
    route_map = frozen_js_map(source, "STATIC_LOCALE_ROUTES")
    expected_routes = {locale: locale for locale in OFFICIAL_LOCALES}
    if list(route_map) != list(OFFICIAL_LOCALES) or route_map != expected_routes:
        errors.append("localize.js: static locale route map is not fixed exact-50")
    if frozen_js_map(source, "STATIC_SURFACES") != {
        "index": "support.html",
        "privacy": "privacy.html",
    }:
        errors.append("localize.js: legacy root surface map mismatch")
    for contract in (
        'preserved.delete("lang")',
        "next.hash = window.location.hash",
        "window.location.replace(target.href)",
    ):
        if contract not in source:
            errors.append(f"localize.js: missing legacy route contract {contract!r}")
    return errors


def lint_identity_and_contact() -> list[str]:
    errors: list[str] = []
    site_files = (
        "index.html", "privacy.html", "terms.html", "robots.txt", "sitemap.xml",
        "styles.css", "locales.js", "localize.js",
    )
    current_metadata_files = [
        CANONICAL_METADATA,
        *FASTLANE_METADATA.glob("*/*.txt"),
        URL_BUILDER,
    ]
    public_sources = [(ROOT / name) for name in site_files] + current_metadata_files
    url_mirrors = list(FASTLANE_METADATA.glob("*/*_url.txt"))
    if BACKUP_METADATA.is_dir():
        url_mirrors.extend(BACKUP_METADATA.glob("*/*_url.txt"))

    for path in public_sources + url_mirrors:
        source = path.read_text(encoding="utf-8")
        folded = source.casefold()
        for token in LEGACY_TOKENS:
            if token in folded:
                errors.append(f"{path}: stale public identity token {token!r}")
        if re.search(r"\b" + "Astrea" + r"\b", source.replace(BUNDLE_ID, "")):
            errors.append(f"{path}: stale public Astrea brand")
        for email in EMAIL_RE.findall(source):
            if email.casefold() != ALLOWED_EMAIL:
                errors.append(f"{path}: disallowed public email {email}")

    site_source = "\n".join(
        (ROOT / name).read_text(encoding="utf-8") for name in site_files
    )
    if site_source.count(BUNDLE_ID) != 1:
        errors.append("privacy bundle ID must appear exactly once on the public site")
    without_bundle = site_source.replace(BUNDLE_ID, "")
    if re.search(r"\b" + "Astrea" + r"\b", without_bundle):
        errors.append("public site contains stale Astrea branding outside the legal bundle ID")
    if BUNDLE_ID not in (ROOT / "privacy.html").read_text(encoding="utf-8"):
        errors.append("privacy.html: missing the registered bundle ID")

    campaigns = re.findall(r"utm_campaign=([^&\"']+)", site_source)
    if not campaigns:
        errors.append("site: missing support-site campaign")
    elif any(campaign != "sup_zodira" for campaign in campaigns):
        errors.append(f"site: campaign mismatch {campaigns}")
    return errors


def lint_metadata_urls(
    locales: dict[str, dict[str, str]],
) -> list[str]:
    errors: list[str] = []
    canonical = json.loads(CANONICAL_METADATA.read_text(encoding="utf-8"))
    if tuple(canonical.get("_meta", {}).get("localeOrder", ())) != OFFICIAL_LOCALES:
        errors.append("canonical metadata localeOrder is not the official exact-50 order")
    if set(canonical) - {"_meta"} != LOCALE_SET:
        errors.append("canonical metadata locale records are not exact-50")

    actual_dirs = {path.name for path in FASTLANE_METADATA.iterdir() if path.is_dir()}
    if actual_dirs != LOCALE_SET:
        errors.append(
            "fastlane metadata locale mismatch "
            f"missing={sorted(LOCALE_SET - actual_dirs)} "
            f"extra={sorted(actual_dirs - LOCALE_SET)}"
        )
    for locale in OFFICIAL_LOCALES:
        expected = {
            "supportUrl": expected_support_url(locale),
            "privacyPolicyUrl": expected_privacy_url(locale),
        }
        record = canonical.get(locale, {})
        for field, value in expected.items():
            if record.get(field) != value:
                errors.append(f"canonical {locale}/{field} must be {value}")
        if locale in locales:
            if locales[locale].get("description") != record.get("description"):
                errors.append(f"locales.js: {locale}/description differs from canonical")
            if locales[locale].get("workflow") != record.get("whatsNew"):
                errors.append(f"locales.js: {locale}/workflow differs from canonical")

        files = {
            "support_url.txt": expected_support_url(locale),
            "privacy_url.txt": expected_privacy_url(locale),
            "marketing_url.txt": expected_support_url(locale),
        }
        for filename, value in files.items():
            path = FASTLANE_METADATA / locale / filename
            actual = path.read_text(encoding="utf-8") if path.is_file() else ""
            if actual != value:
                errors.append(f"{path}: expected {value!r}, found {actual!r}")
            parsed = urlsplit(actual)
            query = parse_qs(parsed.query, strict_parsing=True) if actual else {}
            if query != {"lang": [locale]}:
                errors.append(f"{path}: locale query must be exactly lang={locale}")

    if BACKUP_METADATA.is_dir():
        for path in BACKUP_METADATA.glob("*/*_url.txt"):
            locale = path.parent.name
            if locale not in LOCALE_SET:
                errors.append(f"{path}: unexpected backup locale")
                continue
            expected = (
                expected_privacy_url(locale)
                if path.name == "privacy_url.txt"
                else expected_support_url(locale)
            )
            if path.read_text(encoding="utf-8") != expected:
                errors.append(f"{path}: stale direct URL mirror")
    return errors


def lint_sitemap_and_robots() -> list[str]:
    errors: list[str] = []
    source = (ROOT / "sitemap.xml").read_text(encoding="utf-8")
    urls = re.findall(r"<loc>([^<]+)</loc>", source)
    expected = [
        *PAGES.values(),
        *(
            f"{SITE_ROOT}{locale}/{name}"
            for locale in OFFICIAL_LOCALES
            for name in STATIC_SURFACES
        ),
    ]
    if any(urlsplit(url).query or urlsplit(url).fragment for url in urls):
        errors.append("sitemap.xml: query strings and fragments are forbidden")
    if len(urls) != len(set(urls)):
        errors.append("sitemap.xml: duplicate URL")
    if urls != expected:
        url_set = set(urls)
        expected_set = set(expected)
        errors.append(
            "sitemap.xml: URL mismatch "
            f"missing={sorted(expected_set - url_set)} "
            f"extra={sorted(url_set - expected_set)}"
        )
    robots = (ROOT / "robots.txt").read_text(encoding="utf-8")
    expected_line = f"Sitemap: {SITE_ROOT}sitemap.xml"
    if expected_line not in robots:
        errors.append(f"robots.txt: missing {expected_line}")
    return errors


def main() -> None:
    locales, errors = parse_locales()
    locale_keys = set(next(iter(locales.values()), {}))
    for name, canonical in PAGES.items():
        errors.extend(lint_page(name, canonical, locale_keys))
    errors.extend(lint_root_navs(locales))
    errors.extend(lint_root_static_graph(locales))
    errors.extend(lint_static_surfaces())
    errors.extend(lint_identity_and_contact())
    errors.extend(lint_metadata_urls(locales))
    errors.extend(lint_sitemap_and_robots())
    errors.extend(lint_legacy_router())

    loader = (ROOT / "localize.js").read_text(encoding="utf-8")
    for contract in (
        "URLSearchParams", "STATIC_LOCALE_ROUTES",
        "document.documentElement.dir", "Object.hasOwn(STATIC_LOCALE_ROUTES, requested)",
    ):
        if contract not in loader:
            errors.append(f"localize.js: missing fail-closed locale contract {contract!r}")

    if errors:
        print("\n".join(errors), file=sys.stderr)
        raise SystemExit(1)
    print(
        "site lint passed: canonical identity, exact-50 native dictionary, "
        "localized URLs, mirrors, sitemap, contact and legal bundle exception"
    )


if __name__ == "__main__":
    main()
